"""empty message

Revision ID: 048066f76935
Revises: dee9a9160d97
Create Date: 2024-10-16 10:10:57.408619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '048066f76935'
down_revision: Union[str, None] = 'dee9a9160d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'pk',
               existing_type=mysql.INTEGER(),
               comment='설정 고유 아이디',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'pk',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='설정 고유 아이디',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
