"""empty message

Revision ID: 14c76a7ae159
Revises: 53f842896aaf
Create Date: 2024-11-14 10:50:43.547521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '14c76a7ae159'
down_revision: Union[str, None] = '53f842896aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'pwd',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True,
               existing_comment='암호화')
    op.alter_column('user_info', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='True : 남자, False : 여자')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'gender',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='True : 남자, False : 여자')
    op.alter_column('user_info', 'pwd',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False,
               existing_comment='암호화')
    # ### end Alembic commands ###
