"""empty message

Revision ID: 151ae7c78fad
Revises: c2c6c5a4fa63
Create Date: 2024-11-24 19:13:55.691887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '151ae7c78fad'
down_revision: Union[str, None] = 'c2c6c5a4fa63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'api', 'user_info', ['user_id'], ['user_id'])
    op.add_column('erd', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'erd', 'user_info', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'erd', type_='foreignkey')
    op.drop_column('erd', 'user_id')
    op.drop_constraint(None, 'api', type_='foreignkey')
    op.alter_column('api', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
