"""empty message

Revision ID: 2226a171b0de
Revises: 4a38ac514130
Create Date: 2024-11-24 19:03:32.436455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2226a171b0de'
down_revision: Union[str, None] = '4a38ac514130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'api', ['user_id'])
    op.create_foreign_key(None, 'api', 'notes', ['user_id'], ['user_id'])
    op.add_column('erd', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'erd', ['user_id'])
    op.create_foreign_key(None, 'erd', 'notes', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'erd', type_='foreignkey')
    op.drop_constraint(None, 'erd', type_='unique')
    op.drop_column('erd', 'user_id')
    op.drop_constraint(None, 'api', type_='foreignkey')
    op.drop_constraint(None, 'api', type_='unique')
    op.drop_column('api', 'user_id')
    # ### end Alembic commands ###
