"""empty message

Revision ID: 296c36b86158
Revises: 9307f730245b
Create Date: 2024-11-29 12:04:51.373835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '296c36b86158'
down_revision: Union[str, None] = '9307f730245b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_info', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_user_info_nickname'), 'user_info', ['nickname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_nickname'), table_name='user_info')
    op.alter_column('user_info', 'nickname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
