"""empty message

Revision ID: 35fcd38d34d0
Revises: dc952ac1e4ca
Create Date: 2024-11-30 14:14:41.405423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35fcd38d34d0'
down_revision: Union[str, None] = 'dc952ac1e4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='PK'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 고유 아이디'),
    sa.Column('members', sa.JSON(), nullable=True),
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_group_invite_id'), 'user_group', ['invite_id'], unique=True)
    op.drop_index('ix_group_invite_id', table_name='group')
    op.drop_table('group')
    op.drop_constraint('member_ibfk_1', 'member', type_='foreignkey')
    op.create_foreign_key(None, 'member', 'user_group', ['invite_id'], ['invite_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.create_foreign_key('member_ibfk_1', 'member', 'group', ['invite_id'], ['invite_id'])
    op.create_table('group',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='PK'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='사용자 고유 아이디'),
    sa.Column('members', mysql.JSON(), nullable=True),
    sa.Column('invite_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], name='group_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_group_invite_id', 'group', ['invite_id'], unique=True)
    op.drop_index(op.f('ix_user_group_invite_id'), table_name='user_group')
    op.drop_table('user_group')
    # ### end Alembic commands ###
