"""empty message

Revision ID: 3e04ffa8c4bb
Revises: 59a8e401eaa8
Create Date: 2024-11-23 00:35:43.734394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e04ffa8c4bb'
down_revision: Union[str, None] = '59a8e401eaa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'AI', ['note_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'AI', type_='unique')
    # ### end Alembic commands ###
