"""empty message

Revision ID: 468df19db4b9
Revises: 2ea37dcbf09e
Create Date: 2024-11-28 13:10:36.615541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '468df19db4b9'
down_revision: Union[str, None] = '2ea37dcbf09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='PK'),
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 고유 아이디'),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invite_id'], ['group.invite_id'], ),
    sa.ForeignKeyConstraint(['nickname'], ['user_info.nickname'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('calenders')
    op.alter_column('group', 'invite_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'invite_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_table('calenders',
    sa.Column('calender_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='자동생성'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='사용자 고유 아이디'),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('create_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], name='calenders_ibfk_1'),
    sa.PrimaryKeyConstraint('calender_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('member')
    # ### end Alembic commands ###
