"""empty message

Revision ID: 53f842896aaf
Revises: 71cdd1c44e40
Create Date: 2024-11-14 10:33:17.105819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53f842896aaf'
down_revision: Union[str, None] = '71cdd1c44e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'theme',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=20),
               comment='color string',
               existing_comment='hax color',
               existing_nullable=False)
    op.add_column('user_info', sa.Column('provider_id', sa.String(length=30), nullable=True, comment='Oauth 제공자가 local이 아닌 경우에만 작성'))
    op.add_column('user_info', sa.Column('provider_type', sa.String(length=20), nullable=False, comment='Oauth 제공자 정보'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'provider_type')
    op.drop_column('user_info', 'provider_id')
    op.alter_column('settings', 'theme',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=7),
               comment='hax color',
               existing_comment='color string',
               existing_nullable=False)
    # ### end Alembic commands ###
