"""empty message

Revision ID: 58381085f509
Revises: b5c12fb215a9
Create Date: 2024-11-30 18:27:34.997745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '58381085f509'
down_revision: Union[str, None] = 'b5c12fb215a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('member', 'invite_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('user_group', 'invite_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group', 'invite_id',
               existing_type=sa.String(length=40),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('member', 'invite_id',
               existing_type=sa.String(length=40),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
