"""empty message

Revision ID: 6d8d58787c83
Revises: 5c64592d2df8
Create Date: 2024-10-17 09:34:05.433864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d8d58787c83'
down_revision: Union[str, None] = '5c64592d2df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'pk',
               existing_type=mysql.INTEGER(),
               comment='설정 고유 아이디',
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('settings_ibfk_1', 'settings', type_='foreignkey')
    op.drop_column('settings', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='사용자 고유 아이디'))
    op.create_foreign_key('settings_ibfk_1', 'settings', 'user_info', ['user_id'], ['user_id'])
    op.alter_column('settings', 'pk',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='설정 고유 아이디',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
