"""empty message

Revision ID: 859dbac63159
Revises: 296c36b86158
Create Date: 2024-11-29 12:10:52.965689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859dbac63159'
down_revision: Union[str, None] = '296c36b86158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_info_nickname'), 'user_info', ['nickname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_info_nickname'), table_name='user_info')
    # ### end Alembic commands ###
