"""empty message

Revision ID: 9094b79e2b4b
Revises: 14c76a7ae159
Create Date: 2024-11-23 00:26:34.757277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9094b79e2b4b'
down_revision: Union[str, None] = '14c76a7ae159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('api', sa.Column('created_at', sa.DateTime(), nullable=False, comment='자동'))
    op.add_column('api', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('api', 'api_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='API 명세서 고유 아이디',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('api', 'title',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='노트 제목',
               existing_nullable=True)
    op.create_unique_constraint(None, 'api', ['note_id'])
    op.drop_column('api', 'update_at')
    op.drop_column('api', 'content')
    op.create_unique_constraint(None, 'erd', ['note_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'erd', type_='unique')
    op.add_column('api', sa.Column('content', mysql.TEXT(), nullable=True, comment='내용'))
    op.add_column('api', sa.Column('update_at', mysql.DATETIME(), nullable=False, comment='문서 생성 시각'))
    op.drop_constraint(None, 'api', type_='unique')
    op.alter_column('api', 'title',
               existing_type=mysql.VARCHAR(length=100),
               comment='노트 제목',
               existing_nullable=True)
    op.alter_column('api', 'api_id',
               existing_type=mysql.INTEGER(),
               comment='API 명세서 고유 아이디',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('api', 'updated_at')
    op.drop_column('api', 'created_at')
    op.drop_column('api', 'description')
    # ### end Alembic commands ###
