"""empty message

Revision ID: b88cd4fcc3a9
Revises: 58381085f509
Create Date: 2024-11-30 18:31:22.903752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b88cd4fcc3a9'
down_revision: Union[str, None] = '58381085f509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('member_ibfk_3', 'member', type_='foreignkey')

    # 2. user_group 테이블의 invite_id 컬럼 타입 변경
    op.alter_column('user_group', 'invite_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False)

    # 3. member 테이블의 invite_id 컬럼 타입 변경
    op.alter_column('member', 'invite_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=40),
               existing_nullable=False)

    # 4. 외래 키 제약 조건 다시 추가
    op.create_foreign_key('member_ibfk_3', 'member', 'user_group', ['invite_id'], ['invite_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_group', 'invite_id',
               existing_type=sa.String(length=40),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('member', 'invite_id',
               existing_type=sa.String(length=40),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
