"""empty message

Revision ID: bd402063605b
Revises: ce6fd0eb9db5
Create Date: 2024-11-29 12:42:06.534790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd402063605b'
down_revision: Union[str, None] = 'ce6fd0eb9db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calendars', 'time',
               existing_type=mysql.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('group', 'members',
               existing_type=mysql.INTEGER(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'members',
               existing_type=sa.JSON(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('calendars', 'time',
               existing_type=sa.DATE(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
