"""empty message

Revision ID: bf7b78df271e
Revises: 90352ad20cff
Create Date: 2024-11-30 18:02:13.148643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf7b78df271e'
down_revision: Union[str, None] = '90352ad20cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'teamspace_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'teamspace_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
