"""empty message

Revision ID: ce6fd0eb9db5
Revises: 747f0e973341
Create Date: 2024-11-29 12:35:31.851629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce6fd0eb9db5'
down_revision: Union[str, None] = '747f0e973341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('member_ibfk_2', 'member', type_='foreignkey')
    op.drop_column('member', 'nickname')
    op.drop_index('ix_user_info_nickname', table_name='user_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_info_nickname', 'user_info', ['nickname'], unique=True)
    op.add_column('member', sa.Column('nickname', mysql.VARCHAR(length=20), nullable=False))
    op.create_foreign_key('member_ibfk_2', 'member', 'user_info', ['nickname'], ['nickname'])
    # ### end Alembic commands ###
