"""empty message

Revision ID: e879979df8b2
Revises: 6d8d58787c83
Create Date: 2024-10-17 09:35:02.257904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e879979df8b2'
down_revision: Union[str, None] = '6d8d58787c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='사용자 고유 아이디'),
    sa.Column('theme', mysql.VARCHAR(length=7), nullable=False, comment='hax color'),
    sa.Column('font_size', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('pk', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], name='settings_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
