"""empty message

Revision ID: eecae4ec158f
Revises: 58acb15d44b9
Create Date: 2024-11-24 19:33:42.021642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eecae4ec158f'
down_revision: Union[str, None] = '58acb15d44b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='사용자 고유 아이디',
               existing_comment='노트의 사용자 고유 아이디')
    op.create_foreign_key(None, 'api', 'user_info', ['user_id'], ['user_id'])
    op.add_column('erd', sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 고유 아이디'))
    op.create_foreign_key(None, 'erd', 'user_info', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'erd', type_='foreignkey')
    op.drop_column('erd', 'user_id')
    op.drop_constraint(None, 'api', type_='foreignkey')
    op.alter_column('api', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='노트의 사용자 고유 아이디',
               existing_comment='사용자 고유 아이디')
    # ### end Alembic commands ###
