"""empty message

Revision ID: fdf649edb89c
Revises: 468df19db4b9
Create Date: 2024-11-28 13:14:45.782808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fdf649edb89c'
down_revision: Union[str, None] = '468df19db4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calenders')
    op.alter_column('group', 'invite_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'invite_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_table('calenders',
    sa.Column('calender_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='자동생성'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='사용자 고유 아이디'),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('create_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], name='calenders_ibfk_1'),
    sa.PrimaryKeyConstraint('calender_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
